Table Chains {
  chain_id int [pk, note: "based on chainlist"]
  name string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "Is used to map addresses to a chain. Chain_id (PK) is based on the chain's id (see chainlist)."
}

Table Addresses {
  address unknown [pk]
  chain_id int [pk]
  project_id unknown 
  category_id string
  is_eoa bool
  name string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "Represents wallet and smart contract addresses, linked to chains, projects, and categorization."
}

Table Projects {
  project_id unknown [pk]
  name string
  team_id string
  website string
  docs string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "Information about specific projects (i.e. Uniswap V2), including project name, website link, and documentation."
}

Table Categories {
  category_id string [pk]
  name string
  definition string
  main_category_id string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "A classification system that can be used for grouping contracts and wallets into specific categories."
}

Table MainCategories {
  main_category_id string [pk]
  name string
  definition string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "A higher-level categorization that can group multiple categories under a broader classification."
}

Table TagGroup {
  tag_group_id unknown [pk]
  name string
  description string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "Represents collections of tags that can be applied to other entities in the system for organizational purposes."
}

Table Tags {
  tag_id unknown [pk]
  name string
  tag_group_id unknown
  description string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "Individual labels or identifiers that can be applied to data points for sorting, searching, and categorization purposes."
}

Table TagMapping {
  address unknown 
  tag_id unknown
  
  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "A many-to-many relationship table that maps tags to addresses, allowing an address to have multiple tags and a tag to be applied to multiple addresses."
}

Table Team {
  team_id unknown [pk]
  name string

  created_at timestamp
  created_by string
  modified_at timestamp
  modified_by string

  Note: "A group of people or entities working on projects, with a simple structure containing just an ID and a name."
}

// Relationships
// ManyToManyTagging
Ref: Tags.tag_group_id > TagGroup.tag_group_id
Ref: TagMapping.tag_id > Tags.tag_id
Ref: Addresses.address > TagMapping.address

// OneToManyCategorization
Ref: Categories.main_category_id > MainCategories.main_category_id

// OneToManyProjectsToTeams
Ref: Projects.team_id > Team.team_id

// OneToManyAddressesToChains
Ref: Addresses.chain_id > Chains.chain_id

// OneToManyAddressesToProjects
Ref: Addresses.project_id > Projects.project_id

// OneToManyAddressesToCategories
Ref: Addresses.category_id > Categories.category_id
