Project OLI {
  database_type: 'PostgreSQL'
  Note: '''
    *A standardized framework and data model for EVM address labeling*

    This initiative tackles the issue of isolated and non-standardized datasets of address labels within the blockchain community. It introduces a flexible, open and community owned data framework for anyone to use and contribute to. 

    The OLI repository functions as the community maintainer of the OLI framework. Additionally, it serves as a neutral entity that provides tools for data entry through attestations and automated activity tagging. Find the OLI repo [here](https://github.com/openlabelsinitiative/OLI).
  '''
}

Table Tags {
  tag_id string [pk, Note: "unique identifier for the tag"]
  name string [Note: "descriptive name of the tag"]
  description string [Note: "short explanation of what the tag represents"]
  type string [Note: "data type of the tag: string, boolean, object_array"]
  value_set list [Note: "predefined value set or URL to an external value set"]
  schema jsonb [Note: "JSON schema definition for object and object_array types"]
  creator string [Note: "entity responsible for creating the tag"]
  version float [Note: "version of this tag_id"]

  Note: "Individual tags or identifiers that can be applied to addresses for sorting, searching, and categorization purposes."
}

Table Framework {
  address string [pk, Note: "the hexadecimal public address of a smart contract or externally owned account (EOA)"]
  chain_id string [pk, Note: "unique identifier as defined by EIP-155 or CAIP-2"]
  tag_id string [pk, Note: "Tag IDs that can represent a wide range of concepts. For OLI-compliant tags, please refer to tag_defintions.yml in the OLI github repo"]
  value string [Note: ""]

  Note: "A many-to-many relationship table that maps tags to addresses, allowing an address to have multiple tag_ids and a tag_id to be applied to multiple addresses."
}

Ref: Framework.tag_id > Tags.tag_id